### ISSUE TITLE
Always display all stages in jenkins' (classic) stage view

### ISSUE THREAD

**Issue by jeichler** [RedHatSatellite/soe-ci#106]
the pipeline in Jenkins' classic view (aka the "not blue ocean" view) doesn't display stages which come after a failed stage. Therefore the stage view in the job overview page is lost eveytime the number of executed stages differs.
assuming that blue ocean isn't used everywhere, we need to workaround this behaviour.

related open jenkins issues: https://issues.jenkins-ci.org/browse/JENKINS-43995 , which basically means that the display options per step and stage are limited right now, but it's sufficient.

side note: if stages are added / removed / renamed in the pipeline itself, the stage view loses the history again. but that makes sense.

**Comment by jeichler** [comment]
@pcfe please close this bug once your tests were successful.

**Comment by pcfe** [comment]
Works as intended.
![image](https://user-images.githubusercontent.com/3717066/42581883-0e13b220-852e-11e8-8549-35601ee883fd.png)

**Comment by pcfe** [comment]
![image](https://user-images.githubusercontent.com/3717066/42583420-32b81960-8531-11e8-83d6-d06b0c06ded7.png)

**Comment by pcfe** [comment]
@ericzolf @nstrug is there anything that speaks against finally enabling pipelines and deprecating the old non-pipeline way?

**Comment by jeichler** [comment]
closing since pipelines are now on the master

**Comment by nmz787-intel** [comment]
sorry, what's the fix? My pipeline overview gets limited to 1 sometimes and it is very annoying:
![image](https://github.com/RedHatSatellite/soe-ci/assets/102060486/52d1715b-37dd-4af6-b149-5508897ed246)
