### ISSUE TITLE
Stale parameter MODAUTHOR in Jenkins' config.xml

### ISSUE THREAD

**Issue by ericzolf** [RedHatSatellite/soe-ci#25]
There is a MODAUTHOR parameter defined in config.xml but no script is making use of it. As we would have at a typical customer, Puppet modules coming from different sources, I'm not really sure what the purpose of this would be, hence I'd suggest to remove the parameter and I can do it myself, but before I do, I wanted to be sure I didn't oversee anything.

**Comment by nstrug** [comment]
Confirmed that this is not used. Will need to remove it from config.xml

**Comment by nstrug** [comment]
#90
