### ISSUE TITLE
Unexplained difference between chroot_setup_cmd for RHEL 6 vs. 7 mock configs

### ISSUE THREAD

**Issue by ericzolf** [RedHatSatellite/soe-ci#42]
If I look at the differences between the RHEL 6 and the RHEL 7 config files for mock, regarding config_opts['chroot_setup_cmd'],

common packages are:
 bash
 bzip2
 cpio
 diffutils
 gcc-c++
 gzip
 make
 patch
 rpm-build
 sed
 shadow-utils
 tar
 unzip
 which

Packages only for RHEL 6 are:
-coreutils
-findutils
-gawk
-gcc
-grep
-info
-redhat-release
-redhat-rpm-config
-util-linux-ng
-xz

Packages only for RHEL 7 are:
+gdd
+perl

And I don't understand why there should be such differences.

**Comment by pcfe** [comment]
@ericzolf unsure, these are seemingly old mock configs for epel6 and epel7 that were recycled. (which is correct and what I would have done too)

current lock uses the group @buildsys-build, if you have spare cycles test if that group works for older releases.

If you want I can dig into this deeper, but I do not think it's useful, if that part is wrong the error message from mock is clear.

Should we maybe assign this issue to an owner?
