### ISSUE TITLE
BUILD_URL not populated

### ISSUE THREAD

**Issue by pcfe** [RedHatSatellite/soe-ci#48]
In publishcv.sh the variable BUILD_URL is used but it's empty.
This makes finding a specific build a major pain.
Need to fix this.

"hammer content-view publish --name \"${cv}\" --organization \"${ORG}\" --description \"Build ${BUILD_URL}\""

@nstrug do I assume correctly that this is meant to point to jenkins so that a user can determin which CV version got created by which build job?

@ericzolf you touched that line last according to git, did that ever work for you?

**Comment by ericzolf** [comment]
Yes, it did work, I'm positive. Perhaps it's related to https://issues.jenkins-ci.org/browse/JENKINS-28466 and shows that their Jenkins isn't (yet) properly setup?

**Comment by ericzolf** [comment]
The attached screenshots show how it should look like in my environment, for a CV as well as for a CCV:
![screenshot-showing-commented-ccv](https://cloud.githubusercontent.com/assets/3105685/17183392/87406ba0-5427-11e6-9a9a-f52be49dbd54.jpg)
![screenshot-showing-commented-cv](https://cloud.githubusercontent.com/assets/3105685/17183391/873f079c-5427-11e6-811a-e51b82798e24.jpg)

A search through the configuration Jenkins doesn't show anything specific. The previously given links should help fix the Jenkins configuration.
